server:
  port: 9098

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:9091/eureka

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    hikari:
      schema: pabw_auth
    username: pabw_auth_user
    password: pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: pabw_auth

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  lifetime: 3600000
