version: '2.3'

services:
  debit-service:
    build: ./debit-service
    container_name: debit-service
    environment:
      - 'spring.datasource.url=jdbc:postgresql://postgres_test_db:5432/postgres'
      - 'spring.datasource.hikari.schema=test_schema'
    depends_on:
      - postgres_test_db
    ports:
      - "9099:9099"
  main-service:
    build: ./core-service
    container_name: core-service
    environment:
      - 'spring.datasource.url=jdbc:postgresql://postgres_test_db:5432/postgres'
      - 'spring.datasource.hikari.schema=test_schema'
    depends_on:
      - postgres_test_db
      - discovery-service
    ports:
      - "9090:9090"
  gateway:
    build: ./gateway
    container_name: gateway-service
    depends_on:
      - main-service
      - discovery-service
    ports:
      - "5555:5555"
    environment:
      - 'jwt.secret=h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g'
  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - main-service
      - discovery-service
    ports:
      - "9098:9098"
    environment:
      - 'spring.datasource.url=jdbc:postgresql://postgres_test_db:5432/postgres'
      - 'spring.datasource.hikari.schema=test_schema'
      - 'jwt.secret=h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g'
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "9091:9091"
  front-service:
    build: ./front-service
    container_name: front-service
    ports:
      - "8190:8190"
  postgres_test_db:
    image: postgres:13.2
    container_name: postgres_test_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5435:5432"
