server:
  port: 5555

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://core-service:9090/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuthFilter
        - id: auth-service
          uri: http://auth-service:9098/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-auth
            - JwtAuthFilter
