server:
  port: 5555

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:9091/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuthFilter
        - id: debit-service
          uri: lb://debit-service
          predicates:
            - Path=/debit/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuthFilter'
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/credit/**
          filters:
            - StripPrefix=1
            - PrefixPath=/
            - JwtAuthFilter
