server:
  port: 8998

integrations:
  core-service:
        url: http://core-service


# ежедневно в 00:01
#cron:
#  expression: 0 1 0 * * *

# каждую минуту (Для тестирования)
cron:
  expression: 1 * * * * *

spring:

  application:
    name: debit-service

  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    hikari:
      schema: pabw_debit
    username: pabw_debit_user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: pabw_debit

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:9091/eureka
