server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:9091/eureka

spring:
  application:
      name: core-service
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    hikari:
      schema: pabw_core
    username: pabw_core_user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: pabw_core
